name: fusion
description: A Flutter plugin that manages hybrid stack on Android and iOS.
version: 4.0.0
homepage: https://github.com/gtbluesky/fusion

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
#  pana: ^0.21.25

flutter:
  plugin:
    platforms:
      android:
        package: com.gtbluesky.fusion
        pluginClass: FusionPlugin
      ios:
        pluginClass: FusionPlugin

topics:
  - hybrid